exports.cardList = 'select * from cards where users_user_uid=?'
exports.destList = 'select * from destinations where users_user_uid=?'
exports.addCard = 'insert into cards(card_uid, card_exp, card_com, users_user_uid) values(?, ?, ?, ?)'
exports.updateCard = 'update cards set card_exp=?, card_com=? where card_uid=?'
exports.cardDetail = 'select * from cards where card_uid=?'
exports.deleteCard = 'delete from cards where card_uid=?'
exports.addDest = 'insert into destinations(destination_uid, destination_post, destination_addr, destination_detail, users_user_uid) values(?, ?, ?, ?, ?)'
exports.updateDest = 'update destinations set destination_post=?, destination_addr=? destination_detail=? where destination_uid=?'
exports.destDetail = 'select * from destinations where destination_uid=?'
exports.deleteCard = 'delete from destinations where destination_uid=?'